name: "robin-api"

services:
  robin-api:
    container_name: robin-api
    hostname: robin-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./configs:/root/configs
    restart: unless-stopped
    networks:
      - rha_local
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rha
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rha_local

networks:
  rha_local:
    name: "rha_local_net"

volumes:
    mysql_data:
        name: "rha_mysql_data"