name: "robin-api"

services:
  robin-api:
    container_name: robin-api
    hostname: robin-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - robin-db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: rha 
    volumes:
      - ./configs:/root/configs
    restart: unless-stopped
    networks:
      - rha_local

  robin-db:
    container_name: robin-db
    image: mysql:8.4.0
    cap_add:
      - SYS_NICE
    restart: always
    environment: 
      - MYSQL_DATABASE=rha
      - MYSQL_ROOT_PASSWORD=password
    volumes:
    - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
    db-data:
      driver: local

networks:
  rha_local:
    name: "rha_local_net"
